const faker = require('faker');

module.exports = {
  up: queryInterface =>
    queryInterface.bulkInsert('Books', [
      {
        title: 'Cthulhu',
        author: 'Wes Dreamins',
        categoryId: '3',
        quantity: '21',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/c_scale,h_499,w_325/v1507396542/CLD-front-cover-preview-v4-3-1_e9bolq.jpg',
        ISBN: 1222222,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Star Wars Deathtroopers',
        author: 'Joe Schreiber',
        categoryId: '1',
        quantity: '21',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/c_scale,h_499,w_325/v1507396541/cover_bg_d3mob5.jpg',
        ISBN: 12343432,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Scary or Die',
        author: 'Corbin Bleu',
        categoryId: '3',
        quantity: '21',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/c_scale,h_499,w_325/v1507396540/images_tlhli6.jpg',
        ISBN: 12334542,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Origin',
        author: 'Dan Brown',
        categoryId: '1',
        quantity: '21',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/c_scale,h_499,w_325/v1507396540/9780593078754_cxma9t.jpg',
        ISBN: 12336342,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'A Column of Fire',
        author: 'Ken Follet',
        categoryId: '2',
        quantity: '21',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/c_scale,h_499,w_325/v1507396540/9781447278733_atkrje.jpg',
        ISBN: 123362332,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Decay',
        author: 'Lockhart',
        categoryId: '1',
        quantity: '21',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/c_scale,h_499,w_325/v1507396540/6018732-3x4-700x933_lgudvq.jpg',
        ISBN: 123363432,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Angel of Repose',
        author: 'Wallace Stegner',
        categoryId: '2',
        quantity: '21',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/c_scale,h_499,w_325/v1507396540/9781101872765_aikbtf.jpg',
        ISBN: 1324222,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Capital',
        author: 'Thomas Piketty',
        categoryId: '1',
        quantity: '21',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/c_scale,h_499,w_325/v1507396539/Capital_in_the_First_Century_bc4bfw.webp',
        ISBN: 12163242,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'The House on the Borderland',
        author: 'William Hope Hodgson',
        categoryId: '2',
        quantity: '21',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/c_scale,h_499,w_325/v1507396518/51iMfGw6LcL._AC_UL320_SR202_320__ret7dc.jpg',
        ISBN: 124363242,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Dare',
        author: 'Barry McDonagh',
        categoryId: '2',
        quantity: '23',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/c_scale,h_499,w_325/v1506272698/book_1_gudyxi.jpg',
        ISBN: 121633242,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'A Room Full of Bones',
        author: 'Elly Griffiths',
        categoryId: '5',
        quantity: '21',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/v1506272697/book4_dwjtvv.jpg',
        ISBN: 123343242,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'I am Watching You',
        author: 'Teresa Driscoll',
        categoryId: '1',
        quantity: '25',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/c_scale,h_499,w_399/v1506272698/book2_rxfkg9.jpg',
        ISBN: 133633242,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'The Litigators',
        author: 'John Grisham',
        categoryId: '1',
        quantity: '19',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/c_scale,w_325/v1506272697/book3_cmhfot.jpg',
        ISBN: 123363242,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'End of Watch',
        author: 'Stephen King',
        categoryId: '1',
        quantity: '24',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/v1506272697/book6_v1ufwj.jpg',
        ISBN: 123343242,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'The Redbreast Jo Nesbo',
        author: 'Harry Hole',
        categoryId: '4',
        quantity: '23',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/v1506272697/book5_cpffhx.jpg',
        ISBN: 12333233,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Fix Entrepreneur and you Fix Nigeria',
        author: 'S. K. Ogidan',
        categoryId: '1',
        quantity: '21',
        description: faker.lorem.paragraphs(),
        bookImage: 'http://res.cloudinary.com/digpnxufx/image/upload/c_scale,h_499,w_325/v1511882088/20171115_221213_ltwmmw.png',
        ISBN: 13223242,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]),
  down: queryInterface =>
    queryInterface.bulkDelete('Books', [{
    }])
};
