export const USER_LOGGED_IN = 'USER_LOGGED_IN';

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';

export const FETCH_SELECTED_BOOK_SUCCESS = 'FETCH_SELECTED_BOOK_SUCCESS';

export const FETCH_SELECTED_BOOK_FAILURE = 'FETCH_SELECTED_BOOK_FAILURE';

export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';

export const FETCH_ALL_RECENT_BOOKS = 'FETCH_ALL_RECENT_BOOKS ';

export const FETCH_ALL_BOOKS = 'FETCH_ALL_BOOKS ';

export const FETCH_BORROWED_BOOKS = 'FETCH_BORROWED_BOOKS';

export const FETCH_BOOKS_REJECTED = 'FETCH_BOOKS_REJECTED';

export const FETCH_ALL_OVERDUE_BOOKS = 'FETCH_ALL_OVERDUE_BOOKS';

export const FETCH_ALL_OVERDUE_REJECTED = 'FETCH_ALL_OVERDUE_REJECTED';

export const UPLOAD_TO_CLOUD_IMAGE_SUCCESS = 'UPLOAD_TO_CLOUD_IMAGE_SUCCESS';

export const UPLOAD_TO_CLOUD_IMAGE_FAILURE = 'UPLOAD_TO_CLOUD_IMAGE_FAILURE';

export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS';

export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const FETCH_BOOKS_FOR_CATEGORIES_SUCCESS =
'FETCH_BOOKS_FOR_CATEGORIES_SUCCESS';

export const FETCH_BOOKS_FOR_CATEGORIES_FAILURE =
'FETCH_BOOKS_FOR_CATEGORIES_FAILURE';

export const CLOUDINARY_UPLOAD_PRESET = 'yn0wpv0n';

export const CLOUDINARY_UPLOAD_URL =
'https://api.cloudinary.com/v1_1/digpnxufx/upload';

export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';

export const BORROW_BOOKS_SUCCESS = 'BORROW_BOOKS_SUCCESS';

export const BORROW_BOOKS_FAIL = 'BORROW_BOOKS_FAIL';

export const RETURN_BOOKS_SUCCESS = 'RETURN_BOOKS_SUCCESS';

export const RETURN_BOOKS_FAIL = 'RETURN_BOOKS_FAIL';

export const LOAN_HISTORY_SUCCESS = 'LOAN_HISTORY_SUCCESS';

export const LOAN_HISTORY_FAILURE = 'LOAN_HISTORY_FAILURE';

export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';

export const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE';

export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';

export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';

export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';

export const EDIT_CATEGORY_FAILURE = 'EDIT_CATEGORY_FAILURE';

export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';

export const GET_USER_LIST_FAILURE = 'GET_USER_LIST_FAILURE';

export const GET_USER_LEVEL_LIST_SUCCESS = 'GET_USER_LEVEL_LIST_SUCCESS';

export const GET_USER_LEVEL_LIST_FAILURE = 'GET_USER_LEVEL_LIST_FAILURE';

export const CHANGE_USER_LEVEL_SUCCESS = 'CHANGE_USER_LEVEL_SUCCESS';

export const CHANGE_USER_LEVEL_FAILURE = 'CHANGE_USER_LEVEL_FAILURE';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const PASSWORD_CHANGED_SUCCESS = 'PASSWORD_CHANGED_SUCCESS';

export const PASSWORD_CHANGED_FAILURE = 'PASSWORD_CHANGED_FAILURE';

export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';

export const GET_NOTIFICATIONS_FAILURE = 'GET_NOTIFICATIONS_FAILURE';
