
export const USER_LOGGED_IN = 'USER_LOGGED_IN';

export const USER_LOG_IN_FAILURE = 'USER_LOG_IN_FAILURE';

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const SIGN_UP_USER_FAILURE = 'SIGN_UP_USER_FAILURE';

export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';

export const FETCH_SELECTED_BOOK_SUCCESS = 'FETCH_SELECTED_BOOK_SUCCESS';

export const FETCH_SELECTED_BOOK_FAILURE = 'FETCH_SELECTED_BOOK_FAILURE';

export const FETCH_ALL_RECENT_BOOKS = 'FETCH_ALL_RECENT_BOOKS ';

export const FETCH_ALL_BOOKS = 'FETCH_ALL_BOOKS ';

export const FETCH_BOOKS_BY_USER_ID = 'FETCH_BOOKS_BY_USER_ID';

export const FETCH_BOOKS_REJECTED = 'FETCH_BOOKS_REJECTED';

export const FETCH_ALL_OVERDUE_BOOKS = 'FETCH_ALL_OVERDUE_BOOKS';

export const FETCH_ALL_OVERDUE_REJECTED = 'FETCH_ALL_OVERDUE_REJECTED';

export const UPLOAD_TO_CLOUD_IMAGE_SUCCESS = 'UPLOAD_TO_CLOUD_IMAGE_SUCCESS';

export const UPLOAD_TO_CLOUD_IMAGE_FAILURE = 'UPLOAD_TO_CLOUD_IMAGE_FAILURE';

export const SEARCH_BOOKS_SUCCESS = 'SEARCH_BOOKS_SUCCESS';

export const SEARCH_BOOKS_FAILURE = 'SEARCH_BOOKS_FAILURE';

export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const FETCH_BOOKS_FOR_CATEGORIES_SUCCESS = 'FETCH_BOOKS_FOR_CATEGORIES_SUCCESS';

export const FETCH_BOOKS_FOR_CATEGORIES_FAILURE = 'FETCH_BOOKS_FOR_CATEGORIES_FAILURE';

export const CLOUDINARY_UPLOAD_PRESET = 'yn0wpv0n';

export const CLOUDINARY_UPLOAD_URL = 'https://api.cloudinary.com/v1_1/digpnxufx/upload';

export const BORROW_BOOKS_SUCCESS = 'BORROW_BOOKS_SUCCESS';

export const BORROW_BOOKS_FAIL = 'BORROW_BOOKS_FAIL';

export const RETURN_BOOKS_SUCCESS = 'RETURN_BOOKS_SUCCESS';

export const RETURN_BOOKS_FAIL = 'RETURN_BOOKS_FAIL';

export const LOAN_HISTORY_SUCCESS = 'LOAN_HISTORY_SUCCESS';

export const LOAN_HISTORY_FAILURE = 'LOAN_HISTORY_FAILURE';
