export const USER_LOGGED_IN = "USER_LOGGED_IN"
export const USER_LOGGED_OUT = "USER_LOGGED_OUT"

export const ADD_MESSAGE = "ADD_MESSAGE"

export const USER_SIGN_UP = "USER_SIGN_UP"

export const SET_LOGIN_STATUS =  "SET_LOGIN_STATUS"

export const SAVE_STATE ="SAVE_STATE"

export const GET_SAVED_STATE = "GET_SAVED_STATE"